### PR TITLE
Rename circular_buffer.py to ringdeque.py

### PR DESCRIPTION
**Pull request by nanouasyn**

### CODE REVIEW

**Comment by nanouasyn** [comment]
The .idea directory contains configuration files of the PyCharm project. These files shouldn't be under version control.

**Comment by ickermi** [comment]
I like the first and third commits, but not everyone is satisfied in the second and I would like to make these edits by myself.

**Comment by nanouasyn** [comment]
It's ok now?

**Comment by ickermi** [comment]
Yes, thanks for your work.

**Pull request merged**
